name: dogma_codegen_test
version: 0.1.0
description: Code generation testing for the Dogma libraries.
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  test: ^0.12.3+9
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://dogma-dart.github.io/
